title: Purnachander Gajjalla
logo: /assets/img/purna.jpg
description: 
  <p align="center">
  <a href="https://www.linkedin.com/in/purnachander-gajjalla-7282a211/">LinkedIn</a>
  <a hred="https://www.github.com/gpacju">Github</a>

  <br>
  I'm working on Demand Forecasting and Predictive modelling using Machine Learning models.
  I also work on processing Big data by building and deploying ETL pipelines.
  <br>
  </p>
theme: jekyll-theme-minimal
