title: Purnachander G
logo: /assets/img/purna.jpg
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/purnachander-gajjalla-7282a211/">LinkedIn</a> |
  <a href="https://www.github.com/gpacju/">GitHub</a>
  
  </p>

theme: jekyll-theme-minimal
